# Generated by Django 4.1.6 on 2023-02-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='senha',
        ),
    ]
