# Generated by Django 4.1.6 on 2023-02-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do pedido', 'verbose_name_plural': 'Itens dos pedidos'},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='qtd_total',
            new_name='qtd_valor_total',
        ),
    ]
