# Generated by Django 4.1.6 on 2023-02-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_perfil_usuario_senha'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_endereco',
            name='user_perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.perfil_usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil_endereco',
            name='infomacao',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_endereco',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='perfil_endereco',
            name='trabalho_casa',
            field=models.CharField(choices=[('CS', 'CASA'), ('TR', 'TRABALHO')], default='CS', max_length=2),
        ),
    ]
