# Generated by Django 4.1.6 on 2023-02-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='preco_promocional',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
