# Generated by Django 4.1.6 on 2023-02-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_modelo_preco_alter_modelo_preco_promocional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imgem',
            new_name='imagem',
        ),
    ]
