# Generated by Django 4.1.6 on 2023-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_remove_produto_categoria_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
