from decouple import config


SECRET_KEY = config('SECRET_KEY')

CEPORIGEM = config('CEPORIGEM')

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST= config('EMAIL_HOST')