# Generated by Django 4.1.6 on 2023-02-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.PositiveIntegerField()),
                ('preco_promocional', models.PositiveIntegerField()),
                ('descricao_longa', models.TextField(max_length=500)),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('imgem', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('publico', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('CPU', 'Computadores'), ('PLC', 'Placa Mãe'), ('PRC', 'Processadores'), ('MMR', 'Memoria ram'), ('GAB', 'Gabinites'), ('KIT', 'Kits Gamers'), ('FOT', 'Fontes')], default='CPU', max_length=3)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('preco', models.PositiveIntegerField()),
                ('preco_promocional', models.PositiveIntegerField()),
                ('descricao_curta', models.TextField(blank=True, max_length=200, null=True)),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
    ]
