# Generated by Django 4.1.6 on 2023-02-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_modelo_preco_promocional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('CPU', 'Computadores'), ('PLC', 'Placa Mãe'), ('PRC', 'Processadores'), ('MMR', 'Memoria Ram'), ('GAB', 'Gabinites'), ('KIT', 'Kits Gamers'), ('FOT', 'Fontes'), ('GPU', 'Placa de Video')], default='CPU', max_length=3),
        ),
    ]
