# Generated by Django 4.1.6 on 2023-02-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
