# Generated by Django 4.1.6 on 2023-03-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('produto', '0005_rename_imgem_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria', verbose_name='Categorias'),
        ),
    ]
