# Generated by Django 4.1.6 on 2023-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_produto_altura_produto_comprimento_produto_largura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
