# Generated by Django 4.1.6 on 2023-02-23 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0003_rename_quantidae_itempedido_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='slug',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='qtd_valor_total',
            field=models.CharField(max_length=300, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.CharField(max_length=300, verbose_name='Total de Produtos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
