# Generated by Django 4.1.6 on 2023-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_rename_preco_promo_itempedido_preco_total_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.FloatField(default=0),
        ),
    ]
